name: ml-ids
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - catboost=0.18.1=py37_0
  - click=7.0=py37_0
  - cloudpickle=1.2.2=py_0
  - imbalanced-learn=0.5.0=py_0
  - matplotlib=3.1.1=py37_1
  - mypy=0.750
  - numpy=1.17.2=py37h95a1406_0
  - pandas=0.25.2=py37hb3f55d8_0
  - pip=19.2.3=py37_0
  - pylint=2.4.4
  - pytest=5.2.1=py37_0
  - pytest-runner=5.1=py_0
  - python=3.7.3=h33d41f4_1
  - python-dateutil<2.8.1
  - requests<2.21.0
  - scikit-learn=0.21.3=py37hcdab131_0
  - scipy=1.3.1=py37h921218d_2
  - seaborn=0.9.0=py_1
  - setuptools=41.6.0=py37_1
  - pip:
    - mlflow==1.4
    - sagemaker==1.44.3
    - h5py==2.10.0
    - hyperopt==0.2.2
    - keras==2.3.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - tables==3.6.1
    - tensorflow-estimator==2.0.0
    - tensorflow-gpu==2.0.0
